package polisher;

import atlantis.latex.LaTeXDocument;
import atlantis.tools.Parser;
import atlantis.tools.TextFile;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JScrollPane;
import polisher.analyzer.Analyzer;
import polisher.analyzer.Task;

/**
 *
 * @author cnsaeman
 */
public class MainFrame extends javax.swing.JFrame implements ActionListener {

    public final Resources RSC;
    public final String version;
    
    public final MainSourceView MSV;
    
    public String currentFileName;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(Resources RSC,String version) {
        this.RSC=RSC;
        this.version=version;
        RSC.setMF(this);
        MSV=new MainSourceView(RSC);
        initComponents();
        populateProfileMenu();
        jPanel1.add(new JScrollPane(MSV));
        this.setIconImage(RSC.guiTools.appIcon);
        this.setTitle("Polisher "+version);
        this.setVisible(true);
        RSC.guiTools.scaleAndCenter(this, this, 800, 600, RSC.guiScaleFactor);
        currentFileName=null;
        setDefaults();
    }
    
    public void populateProfileMenu() {
        jMConfiguration.removeAll();
        for (Profile profile : RSC.profiles) {
            JRadioButtonMenuItem jRBI = new JRadioButtonMenuItem(profile.get("Name"));
            jRBI.addActionListener(this);
            jMConfiguration.add(jRBI);
            profileGroup.add(jRBI);
        }        
    }
    
    public void loadFile() {
        String fileName=RSC.guiTools.selectFileForOpen("Select file", "LaTeX file open", ".tex", "LaTeX file");
        if (fileName!=null) {
            currentFileName=fileName;
            MSV.setDocument(LaTeXDocument.fromFile(fileName));
            MSV.updateDisplay();
        }
    }
    
    public void reLoad() {
        if (currentFileName!=null) {
            MSV.setDocument(LaTeXDocument.fromFile(currentFileName));
            MSV.updateDisplay();
        }
    }
    
    public void displayPosition(int row, int column) {
        jLPosition.setText("Position: "+column+":"+row);
    }
    
    private void setDefaults() {
        profileGroup.getElements().nextElement().doClick();
    }
    
    public void showProblemText(String description) {
        jEPStatus.setText(description);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEPStatus = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLPosition = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        problemNumberLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMILoad = new javax.swing.JMenuItem();
        jMIReload = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MIIncreaseFontSize = new javax.swing.JMenuItem();
        MIDecreaseFontSize = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMIFullRun = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMConfiguration = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIShowLaTeXStructure = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setViewportView(jEPStatus);

        jPanel6.add(jScrollPane2);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLPosition.setText("Position");
        jPanel4.add(jLPosition);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel5.add(problemNumberLabel);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("File");

        jMILoad.setText("Open source");
        jMILoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILoadActionPerformed(evt);
            }
        });
        jMenu1.add(jMILoad);

        jMIReload.setText("Reload");
        jMIReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIReloadActionPerformed(evt);
            }
        });
        jMenu1.add(jMIReload);
        jMenu1.add(jSeparator1);

        jMenuItem5.setText("Run tests");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("View");

        MIIncreaseFontSize.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PLUS, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MIIncreaseFontSize.setText("Increase font size");
        MIIncreaseFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIIncreaseFontSizeActionPerformed(evt);
            }
        });
        jMenu6.add(MIIncreaseFontSize);

        MIDecreaseFontSize.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MIDecreaseFontSize.setText("Decrease font size");
        MIDecreaseFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDecreaseFontSizeActionPerformed(evt);
            }
        });
        jMenu6.add(MIDecreaseFontSize);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Analyze");

        jMIFullRun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMIFullRun.setText("Full run, mark errors");
        jMIFullRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFullRunActionPerformed(evt);
            }
        });
        jMenu5.add(jMIFullRun);
        jMenu5.add(jSeparator3);

        jMenuItem12.setText("Full run, text output");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Navigate");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_UP, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("First problem");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Previous problem");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setText("Next problem");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_DOWN, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setText("Last problem");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profiles");

        jMConfiguration.setText("Choose profiles");
        jMenu3.add(jMConfiguration);
        jMenu3.add(jSeparator2);

        jMenuItem7.setText("Create new profile");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Fill in defaults in current profile");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);
        jMenu3.add(jSeparator4);

        jMenuItem11.setText("Reload current profile");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tools");

        jMIShowLaTeXStructure.setText("Show LaTeX Structure");
        jMIShowLaTeXStructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIShowLaTeXStructureActionPerformed(evt);
            }
        });
        jMenu4.add(jMIShowLaTeXStructure);

        jMenuItem10.setText("Test regular expression");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        Help.setText("Help");

        jMenuItem6.setText("Manual");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Help.add(jMenuItem6);

        jMenuItem9.setText("About");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Help.add(jMenuItem9);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMILoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILoadActionPerformed
        loadFile();
    }//GEN-LAST:event_jMILoadActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MSV.moveToPreviousProblem();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMIReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIReloadActionPerformed
        reLoad();
    }//GEN-LAST:event_jMIReloadActionPerformed

    private void jMIShowLaTeXStructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIShowLaTeXStructureActionPerformed
        RSC.guiTools.showLongInformation("LaTeX structure", MSV.highlighter.document.toString(),false);
    }//GEN-LAST:event_jMIShowLaTeXStructureActionPerformed

    private void jMIFullRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFullRunActionPerformed
        Task task=(new Analyzer(MSV,RSC,-1)).run();
        MSV.setProblems(task.problems);
        MSV.updateSyntaxHighlighting();
        MSV.moveToFirstProblem();
    }//GEN-LAST:event_jMIFullRunActionPerformed

    private void MIDecreaseFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDecreaseFontSizeActionPerformed
        MSV.decreaseFontSize();
    }//GEN-LAST:event_MIDecreaseFontSizeActionPerformed

    private void MIIncreaseFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIIncreaseFontSizeActionPerformed
        MSV.increaseFontSize();
    }//GEN-LAST:event_MIIncreaseFontSizeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MSV.moveToFirstProblem();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        MSV.moveToNextProblem();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MSV.moveToLastProblem();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO
        RSC.guiTools.showWarning("ERROR", "NOT IMPLEMENTED YET.");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        RSC.activeProfile.writeBack();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        RSC.guiTools.showLongInformation("About Polisher", RSC.ABOUT_STRING, true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        String link="./Manual/manualv1.pdf";
        try {
            java.awt.Desktop.getDesktop().open(new File(link));
        } catch (IOException ex) {
            RSC.outEx(ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        RegExpTester RET=new RegExpTester(RSC);
        RSC.guiTools.centerDialog(RET);
        RET.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        RSC.switchProfileTo(RSC.activeProfile);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Task task=(new Analyzer(MSV,RSC,-1)).run();
        String fileName="problems in "+Parser.cutFromLast(currentFileName,"/")+".txt";
        TextFile.writeStringToFile(task.getProblems(), fileName);
        RSC.guiTools.showInformation("Analysis complete", "A list of problems has been written to the file\n\""+fileName+"\"");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem MIDecreaseFontSize;
    private javax.swing.JMenuItem MIIncreaseFontSize;
    private javax.swing.JEditorPane jEPStatus;
    private javax.swing.JLabel jLPosition;
    private javax.swing.JMenu jMConfiguration;
    private javax.swing.JMenuItem jMIFullRun;
    private javax.swing.JMenuItem jMILoad;
    private javax.swing.JMenuItem jMIReload;
    private javax.swing.JMenuItem jMIShowLaTeXStructure;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    public javax.swing.JLabel problemNumberLabel;
    private javax.swing.ButtonGroup profileGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        int i=0;
        for (Enumeration<AbstractButton> buttons = profileGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                RSC.switchProfileTo(RSC.profiles.get(i));
            }
            i++;
        }
    }


}
