package atlantis.gui;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author  cnsaeman
 */
public class SingleLineEditor extends javax.swing.JDialog {
    
    public String text;
    public String pre;
    public boolean content;
    public boolean cancelled;
    public boolean password;
    
    /**
     * Creates a new single line editor
     * 
     * @param guiTools
     * @param title
     * @param text
     * @param content 
     */
    public SingleLineEditor(GuiTools guiTools, String title, String text, boolean content) {
        super(guiTools.MF, true);
        setIconImage(guiTools.appIcon);
        this.setTitle(title);
        this.text=text;
        initComponents();
        pre=text;
        this.content=content;
        cancelled=true;
        if (!content) jText.setForeground(AtlantisColors.LIGHTGRAY2);
        jPanel1.setBorder(BorderFactory.createEmptyBorder(guiTools.guiScale(5), guiTools.guiScale(5), guiTools.guiScale(5), guiTools.guiScale(5)));
        jText.setText(text);
        jText.setCaretPosition(text.length());
        jPanel1.add(jText);
        jPanel1.setMinimumSize(new Dimension(guiTools.guiScale(300),guiTools.guiScale(10)));
        jPanel1.setPreferredSize(new Dimension(guiTools.guiScale(300),guiTools.guiScale(30)));
        this.pack();
        guiTools.centerDialog(this);
    }
    
    /**
     * Creates a new single line editor
     * 
     * @param guiTools
     * @param title
     * @param text
     * @param content 
     */
    public SingleLineEditor(GuiTools guiTools, String title, String text, boolean content, JFrame frame) {
        super(frame, true);
        setIconImage(guiTools.appIcon);
        this.setTitle(title);
        this.text=text;
        initComponents();
        pre=text;
        this.content=content;
        cancelled=true;
        if (!content) jText.setForeground(AtlantisColors.LIGHTGRAY2);
        jPanel1.setBorder(BorderFactory.createEmptyBorder(guiTools.guiScale(5), guiTools.guiScale(5), guiTools.guiScale(5), guiTools.guiScale(5)));
        jText.setText(text);
        jText.setCaretPosition(text.length());
        jPanel1.add(jText);
        jPanel1.setMinimumSize(new Dimension(guiTools.guiScale(300),guiTools.guiScale(10)));
        jPanel1.setPreferredSize(new Dimension(guiTools.guiScale(300),guiTools.guiScale(30)));
        this.pack();
        guiTools.centerDialog(this);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnCancel = new javax.swing.JButton();
        jBtnApply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextKeyPressed(evt);
            }
        });
        jPanel1.add(jText);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnCancel.setText("Cancel");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCancel);

        jBtnApply.setText("Apply");
        jBtnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApplyActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnApply);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApplyActionPerformed
        text=jText.getText();
        cancelled=false;
        setVisible(false);
    }//GEN-LAST:event_jBtnApplyActionPerformed

    private void jTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKeyPressed
       if (!content) {
            content=true;
            jText.setForeground(java.awt.Color.BLACK);
            jText.setText("");
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            jBtnApplyActionPerformed(null);
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE)
            jBtnCancelActionPerformed(null);
    }//GEN-LAST:event_jTextKeyPressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApply;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables
    
}
